// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: api/proto/orders/orders.proto

package ordersv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_PENDING                  OrderStatus = 1
	OrderStatus_PAID                     OrderStatus = 2
	OrderStatus_SHIPPED                  OrderStatus = 3
	OrderStatus_CANCELED                 OrderStatus = 4
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "PENDING",
		2: "PAID",
		3: "SHIPPED",
		4: "CANCELED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"PENDING":                  1,
		"PAID":                     2,
		"SHIPPED":                  3,
		"CANCELED":                 4,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_orders_orders_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_api_proto_orders_orders_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_orders_orders_proto_rawDescGZIP(), []int{0}
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`       // артикул
	Qty           uint32                 `protobuf:"varint,2,opt,name=qty,proto3" json:"qty,omitempty"`      // количество
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"` // цена за единицу (в валюте заказа)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_api_proto_orders_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orders_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_api_proto_orders_orders_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItem) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *OrderItem) GetQty() uint32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *OrderItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=orders.v1.OrderStatus" json:"status,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	Amount        float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`   // итоговая сумма
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"` // "USD", "KZT" и т.п.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_api_proto_orders_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_orders_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_api_proto_orders_orders_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Order) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_api_proto_orders_orders_proto protoreflect.FileDescriptor

const file_api_proto_orders_orders_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/orders/orders.proto\x12\torders.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"E\n" +
	"\tOrderItem\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x10\n" +
	"\x03qty\x18\x02 \x01(\rR\x03qty\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\"\x83\x02\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12.\n" +
	"\x06status\x18\x03 \x01(\x0e2\x16.orders.v1.OrderStatusR\x06status\x12*\n" +
	"\x05items\x18\x04 \x03(\v2\x14.orders.v1.OrderItemR\x05items\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt*]\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\b\n" +
	"\x04PAID\x10\x02\x12\v\n" +
	"\aSHIPPED\x10\x03\x12\f\n" +
	"\bCANCELED\x10\x042A\n" +
	"\x06Orders\x127\n" +
	"\vCreateOrder\x12\x10.orders.v1.Order\x1a\x16.google.protobuf.EmptyB,Z*github.com/your/module/gen/orders;ordersv1b\x06proto3"

var (
	file_api_proto_orders_orders_proto_rawDescOnce sync.Once
	file_api_proto_orders_orders_proto_rawDescData []byte
)

func file_api_proto_orders_orders_proto_rawDescGZIP() []byte {
	file_api_proto_orders_orders_proto_rawDescOnce.Do(func() {
		file_api_proto_orders_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_orders_orders_proto_rawDesc), len(file_api_proto_orders_orders_proto_rawDesc)))
	})
	return file_api_proto_orders_orders_proto_rawDescData
}

var file_api_proto_orders_orders_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_orders_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_orders_orders_proto_goTypes = []any{
	(OrderStatus)(0),              // 0: orders.v1.OrderStatus
	(*OrderItem)(nil),             // 1: orders.v1.OrderItem
	(*Order)(nil),                 // 2: orders.v1.Order
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 4: google.protobuf.Empty
}
var file_api_proto_orders_orders_proto_depIdxs = []int32{
	0, // 0: orders.v1.Order.status:type_name -> orders.v1.OrderStatus
	1, // 1: orders.v1.Order.items:type_name -> orders.v1.OrderItem
	3, // 2: orders.v1.Order.created_at:type_name -> google.protobuf.Timestamp
	2, // 3: orders.v1.Orders.CreateOrder:input_type -> orders.v1.Order
	4, // 4: orders.v1.Orders.CreateOrder:output_type -> google.protobuf.Empty
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_orders_orders_proto_init() }
func file_api_proto_orders_orders_proto_init() {
	if File_api_proto_orders_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_orders_orders_proto_rawDesc), len(file_api_proto_orders_orders_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_orders_orders_proto_goTypes,
		DependencyIndexes: file_api_proto_orders_orders_proto_depIdxs,
		EnumInfos:         file_api_proto_orders_orders_proto_enumTypes,
		MessageInfos:      file_api_proto_orders_orders_proto_msgTypes,
	}.Build()
	File_api_proto_orders_orders_proto = out.File
	file_api_proto_orders_orders_proto_goTypes = nil
	file_api_proto_orders_orders_proto_depIdxs = nil
}
