global:
  scrape_interval: 3s
  evaluation_interval: 3s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "your_app"
    static_configs:
      - targets: ["backend:9100"]
