apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9100
    isDefault: true
    jsonData:
      timeInterval: 15s
    editable: true
