// Code generated by "enumer -type=LogFormat -text -json -trimprefix LogFormat -transform=snake -output log_format_enumer.go -comment logger output format"; DO NOT EDIT.

// logger output format
package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _LogFormatName = "textjson"

var _LogFormatIndex = [...]uint8{0, 4, 8}

const _LogFormatLowerName = "textjson"

func (i LogFormat) String() string {
	if i >= LogFormat(len(_LogFormatIndex)-1) {
		return fmt.Sprintf("LogFormat(%d)", i)
	}
	return _LogFormatName[_LogFormatIndex[i]:_LogFormatIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _LogFormatNoOp() {
	var x [1]struct{}
	_ = x[LogFormatText-(0)]
	_ = x[LogFormatJSON-(1)]
}

var _LogFormatValues = []LogFormat{LogFormatText, LogFormatJSON}

var _LogFormatNameToValueMap = map[string]LogFormat{
	_LogFormatName[0:4]:      LogFormatText,
	_LogFormatLowerName[0:4]: LogFormatText,
	_LogFormatName[4:8]:      LogFormatJSON,
	_LogFormatLowerName[4:8]: LogFormatJSON,
}

var _LogFormatNames = []string{
	_LogFormatName[0:4],
	_LogFormatName[4:8],
}

// LogFormatString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func LogFormatString(s string) (LogFormat, error) {
	if val, ok := _LogFormatNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _LogFormatNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to LogFormat values", s)
}

// LogFormatValues returns all values of the enum
func LogFormatValues() []LogFormat {
	return _LogFormatValues
}

// LogFormatStrings returns a slice of all String values of the enum
func LogFormatStrings() []string {
	strs := make([]string, len(_LogFormatNames))
	copy(strs, _LogFormatNames)
	return strs
}

// IsALogFormat returns "true" if the value is listed in the enum definition. "false" otherwise
func (i LogFormat) IsALogFormat() bool {
	for _, v := range _LogFormatValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for LogFormat
func (i LogFormat) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for LogFormat
func (i *LogFormat) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("LogFormat should be a string, got %s", data)
	}

	var err error
	*i, err = LogFormatString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for LogFormat
func (i LogFormat) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for LogFormat
func (i *LogFormat) UnmarshalText(text []byte) error {
	var err error
	*i, err = LogFormatString(string(text))
	return err
}
