// Code generated by "enumer -type=IsoLevel -text -json -trimprefix IsoLevel -transform=snake -output tx_iso_level_enumer.go -comment transactions isolation levels"; DO NOT EDIT.

// transactions isolation levels
package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _IsoLevelName = "read_commitedrepeatable_readserializable"

var _IsoLevelIndex = [...]uint8{0, 13, 28, 40}

const _IsoLevelLowerName = "read_commitedrepeatable_readserializable"

func (i IsoLevel) String() string {
	if i >= IsoLevel(len(_IsoLevelIndex)-1) {
		return fmt.Sprintf("IsoLevel(%d)", i)
	}
	return _IsoLevelName[_IsoLevelIndex[i]:_IsoLevelIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _IsoLevelNoOp() {
	var x [1]struct{}
	_ = x[IsoLevelReadCommited-(0)]
	_ = x[IsoLevelRepeatableRead-(1)]
	_ = x[IsoLevelSerializable-(2)]
}

var _IsoLevelValues = []IsoLevel{IsoLevelReadCommited, IsoLevelRepeatableRead, IsoLevelSerializable}

var _IsoLevelNameToValueMap = map[string]IsoLevel{
	_IsoLevelName[0:13]:       IsoLevelReadCommited,
	_IsoLevelLowerName[0:13]:  IsoLevelReadCommited,
	_IsoLevelName[13:28]:      IsoLevelRepeatableRead,
	_IsoLevelLowerName[13:28]: IsoLevelRepeatableRead,
	_IsoLevelName[28:40]:      IsoLevelSerializable,
	_IsoLevelLowerName[28:40]: IsoLevelSerializable,
}

var _IsoLevelNames = []string{
	_IsoLevelName[0:13],
	_IsoLevelName[13:28],
	_IsoLevelName[28:40],
}

// IsoLevelString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func IsoLevelString(s string) (IsoLevel, error) {
	if val, ok := _IsoLevelNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _IsoLevelNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to IsoLevel values", s)
}

// IsoLevelValues returns all values of the enum
func IsoLevelValues() []IsoLevel {
	return _IsoLevelValues
}

// IsoLevelStrings returns a slice of all String values of the enum
func IsoLevelStrings() []string {
	strs := make([]string, len(_IsoLevelNames))
	copy(strs, _IsoLevelNames)
	return strs
}

// IsAIsoLevel returns "true" if the value is listed in the enum definition. "false" otherwise
func (i IsoLevel) IsAIsoLevel() bool {
	for _, v := range _IsoLevelValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for IsoLevel
func (i IsoLevel) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for IsoLevel
func (i *IsoLevel) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("IsoLevel should be a string, got %s", data)
	}

	var err error
	*i, err = IsoLevelString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for IsoLevel
func (i IsoLevel) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for IsoLevel
func (i *IsoLevel) UnmarshalText(text []byte) error {
	var err error
	*i, err = IsoLevelString(string(text))
	return err
}
